defen_seq = ['KTCENLADTFRGPCFTDGSCDDHCKNKEHLIKGRCRDDFRCWCTRNC','ATCDLASGFGVGSSLCAAHCLVKGYRGGYCKNKICHCRDKF','ATCDLASGFGVGSSLCAAHCIARRYRGGYCNSKAVCVCRN','ATCDLASIFNVNHALCAAHCIARRYRGGYCNSKAVCVCRN',
'ATCDLASKWNWNHTLCAAHCIARRYRGGYCNSKAVCVCRN','ATCDLASFSSQWVTPNDSLCAAHCIARRYRGGYCNGKRVCVCR', 'ATCDLASFSSQWVTPNDSLCAAHCLVKGYRGGYCKNKICHCRDKF', 'ATCDLASFSSQWVTPNDSLCAAHCLVKGYRGGYCKNKICHCRDKF']


comp = []
for i in defen_seq:
    comp.append(len(i))

count = 0
for n in comp:
    if n == min(comp):
        count += 1
        index = comp.index(n)
defen_short = defen_seq[index:index + count]
print(defen_short)

for m in range(count):
    print(len(defen_short[m]))
